### ISSUE TITLE
Single result search that redirects finds no items

### ISSUE THREAD

**Issue by ZeroQI** [tomfin46/IFDB.bundle#2]
searching for "hunger games" return one search on http://ifdb.fanedit.org/ 

2016-04-16 12:17:08,535 (-bbdc4c0) :  INFO (sandbox:19) - For Url: http://ifdb.fanedit.org/fanedit-search/search-results/?query=all&scope=title&keywords=Hunger+Games&order=alpha

in the browser this URL reloads in http://ifdb.fanedit.org/the-hunger-games-mockingjay-the-hanging-tree/. 
I believe the fact it reloads automatically the right page if only 1 item is found cause this issue

Please update on https://forums.plex.tv/discussion/comment/1167953#Comment_1167953 if you can

**Comment by tomfin46** [comment]
Weird it should handle those redirects for single results. I'll take a quick look and see what's going on

Since it's not an official API or anything and I'm just scraping the returned HTML it can result in a few edge cases that don't conform to what the agents expects to see.

Also didn't realise the original plex forums thread had any activity so i'll be sure to go report back there and update on what's going on
